baseurl = "https://synclue.com/"
languageCode = "zh-cn"
title = "picobird's blog"
paginate = 8
ga = "UA-123-45"
disqusShortname = 'synclue'

# theme
#theme = "crisp"
theme = 'journal'

[permalinks]
	post = "/:year/:title/"
	addendum = "/addendum/:year/:title"
