baseurl = ""
languageCode = "zh-cn"
title = "picobird's blog"
paginate = 8
ga = "UA-123-45"
disqusShortname = 'synclue'

# theme
theme = "coder"


[permalinks]
	post = "/:year/:title/"
	addendum = "/addendum/:year/:title"
